version: "3.9"

services:
  front:
    container_name: login-front
    build:
      context: ./front
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    command: sh -c "cd app && yarn start"
  api:
    container_name: login-api
    build:
      context: ./api
  db:
    container_name: login-db
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306